ERP_Components/Controllers/WeaverController.cs
using ERP_Component_DAL.Services;
using Microsoft.AspNetCore.Mvc;
using ERP_Component_DAL.Models;

namespace ERP_Components.Controllers
{
    public class WeaverController : Controller
    {
        private readonly ILogger<WeaverController> _logger;
        private readonly UserServices _userServices;

        private readonly WeaverServices weaverServices;
        private readonly IConfiguration _configuration;


        public WeaverController(ILogger<WeaverController> logger, IConfiguration configuration)
        {

            _logger = logger;
            _configuration = configuration;
            _userServices = new UserServices(configuration);
            weaverServices = new WeaverServices(configuration);
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult WeaverDashboard()
        {
            return View();
        }
        public IActionResult AddWeaver()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddWeaverDetails(Worker worker)
        {
            try
            {
                weaverServices.SaveWorker(worker);
                return RedirectToAction("AddWeaver");
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }
        public IActionResult ViewWeaver()
        {
            var workers = new Worker();
            workers.Weavers = weaverServices.FindWorkers(WorkerType.Weaver);
            workers.Dyers = weaverServices.FindWorkers(WorkerType.Dyer);
            
            return View(workers);
        }

        public IActionResult EditWorker(Guid id)
        {
            //change the model to worker and update the services 
            Worker model = weaverServices.GetWorkerDetailsById(id);
            model.WorkerId = id;
            return View(model);
        }


        [HttpPost]
        public IActionResult EditWorkerDetails(Worker worker)
        {
            weaverServices.UpdateWorker(worker);
            return RedirectToAction("ViewWeaver");
        }
        public IActionResult DeleteWorker(Guid id)
        {
            weaverServices.DeleteWeaver(id);
            return RedirectToAction("ViewWeaver");
        }

        //Bhaii ek baar isko bhi dekh lena ye controller ab completed work orders bhi return kar raha hai
        //Or kisi bhi service ya controller ko chhedna mat 
        //Agar koi problem hui toh mujhe bata dena pehle
        //View work order mai ek completed ka button de dena
        public IActionResult WorkOrder()
        {
            List<Weaver> PendingWorkOrder = weaverServices.ViewWorkOrder(WorkOrderStatuses.PENDING);
            List<Weaver> OngoingWorkOrder = weaverServices.ViewWorkOrder(WorkOrderStatuses.UNDER_PROGRESS);
            List<Weaver> CompletedWorkOrder = weaverServices.ViewWorkOrder(WorkOrderStatuses.COMPLETED);
            var WorkOrder = new Weaver
            {
                PendingWorkOrder = PendingWorkOrder,
                OngoingWorkOrder = OngoingWorkOrder,
                CompletedWorkOrder = CompletedWorkOrder
            };
            return View(WorkOrder);
        }

        //Isko call karlena Dispatch button par
        public IActionResult AllocateToWarehouse(Guid WorkOrderId)
        {
            weaverServices.AllocateToWarehouse(WorkOrderId);

            return RedirectToAction("ViewCompletedWorkOrder");
        }

        public IActionResult StartWeaving(Guid WorkOrderId)
        {
            Guid CenterID = Guid.Parse(HttpContext.Session.GetString("CenterID"));
            Weaver workOrders = weaverServices.ViewProductOfStartWeaving(WorkOrderId, CenterID);

            List<Weaver> weaver = weaverServices.GetRequiredMaterial(WorkOrderId, CenterID);

            var workOrder = new Weaver
            {
                WorkOrderId = WorkOrderId,
                WorkOrderSeries = workOrders.WorkOrderSeries,
                ProductName = workOrders.ProductName,
                Quantity = workOrders.requiredQuantity,
                Specification = workOrders.Specification,
                MaterialRequired = weaver
            };
            return View(workOrder);
        }

        

        public JsonResult ViewWorkOrderItems(Weaver weaver)
        {

            Weaver workOrders = weaverServices.ViewProductOfWorkOrder(weaver.WorkOrderId);
            return Json(workOrders);
        }

        public IActionResult InventoryForAll()

        {
            List<Items> ProductionMaterial = weaverServices.GetProductionMaterial();
            List<Items> WeaverMaterial = weaverServices.GetWeaverMaterial();
            List<Items> finishedProduct = weaverServices.GetWeaverProduct();

            var model = new Items();
            {
                model.ProductionMaterial = ProductionMaterial;
                model.WeaverMaterial = WeaverMaterial;
                model.FinishedProduct = finishedProduct;
            }
             ;

            return View(model);
        }
        public IActionResult ViewPhases(Guid WorkOrderId)
        {
            Guid CenterID = Guid.Parse(HttpContext.Session.GetString("CenterID"));
            Weaver workOrders = weaverServices.ViewProductOfStartWeaving(WorkOrderId, CenterID);
            workOrders = weaverServices.GetPhases(workOrders);

            List<Weaver> weaver = weaverServices.GetWeavers();
            List<Weaver> Dyer = weaverServices.GetDyer();
            List<YarnInfo> yarns = weaverServices.GetYarnDetails(workOrders.ProductId);
            
            var workOrder = new Weaver
            {
                WorkOrderId = WorkOrderId,
                WorkOrderSeries = workOrders.WorkOrderSeries,
                ProductName = workOrders.ProductName,
                Quantity = workOrders.requiredQuantity,
                Specification = workOrders.Specification,
                Weavers = weaver,
                Dyer = Dyer,
                workOrderPhases = workOrders.workOrderPhases,
                AllocatedQuantity = workOrders.AllocatedQuantity,
                dyeingQuantity = workOrders.dyeingQuantity,
                receivedQuantity = workOrders.receivedQuantity,
                Yarns= yarns,
                WorkStatus = workOrders.WorkStatus
            };

            return View(workOrder);
        }


        public IActionResult ViewCompletedWorkOrder()
        {
            List<Weaver> CompletedWorkOrder = weaverServices.ViewWorkOrder(WorkOrderStatuses.COMPLETED);

            //List<Weaver> weaver = weaverServices.ViewCompletedWorkOrder();
            return View(CompletedWorkOrder);
        }
        public IActionResult MaterialRequisitionforWeaver(Guid WorkOrderId)
        {
            Guid CenterID = Guid.Parse(HttpContext.Session.GetString("CenterID"));
            Weaver workOrders = weaverServices.ViewProductOfStartWeaving(WorkOrderId, CenterID);

            List<Weaver> weaver = weaverServices.GetRequiredMaterial(WorkOrderId, CenterID);

            var workOrder = new Weaver
            {
                WorkOrderId = WorkOrderId,
                WorkOrderSeries = workOrders.WorkOrderSeries,
                ProductName = workOrders.ProductName,
                Quantity = workOrders.requiredQuantity,
                Specification = workOrders.Specification,
                MaterialRequired = weaver
            };
            return View(workOrder);
        }
        public  IActionResult SaveMaterialRequisition(Weaver weaver)
        {
           
                weaverServices.InsertMaterialRequisition(weaver);
            return RedirectToAction("WorkOrder");
           
        }
        public IActionResult AllocateToWeaver(AllocatedWork allocatedWork)
        {
            Guid CenterID = Guid.Parse(HttpContext.Session.GetString("CenterID"));
            weaverServices.AllocateToWeaver(allocatedWork, CenterID);
            return RedirectToAction("ViewPhases", new { WorkOrderId = allocatedWork.WorkOrderID });
        }
        public IActionResult AllocateToDeyer()
        {
            VeiwOrdersReadyForDyeing veiwOrdersReadyForDyeing = weaverServices.GetOrdersWithCompletedWeavingProducts();
            return View(veiwOrdersReadyForDyeing);
        }

        // tushar ye action call to ho raha hai lekin ismey data nahi araha
        // ek baar ye vala model check kar liyo or ismey data send kar dena 
        // frontend say; bas vo pop up se send kar diyo bhaii
        public IActionResult Allocationfordying(DyeingOrder dyeingOrder)
        {
            // ye service dyer lo allocatekarney ke liye likhi hai
            weaverServices.AllocateToDyer(dyeingOrder);
            return RedirectToAction("ViewPhases", new { WorkOrderId = dyeingOrder.WorkOrderID });
        }
        public IActionResult SendingForDying()
        {
           Weaver weavers = new Weaver();
            return View(weavers);
        }
        public IActionResult MoveToOngoing(Weaver weaver)
        {
            weaverServices.UpdateWorkOrderStatus(weaver.WorkOrderId, WorkOrderStatuses.UNDER_PROGRESS);
            return RedirectToAction("WorkOrder");
        }


        //Bhaii ye waala controller call kar lena WorkOrder Complete ke liye
        public IActionResult WorkOrderCompleted(Guid workOrderID)
        {
            weaverServices.UpdateWorkOrderStatus(workOrderID, WorkOrderStatuses.COMPLETED);
            return RedirectToAction("WorkOrder");
        }

        //ye jo bhi weaving orders hain vo jo weaver ko allocatekiye hain unko view karney ke liye hai
        public IActionResult ViewWeavingOrders()
        {
            AllocatedWork allocatedWork = new AllocatedWork();
            allocatedWork.allocatedWorks =  weaverServices.FindWeavingOrders();
            return View(allocatedWork);
        }

        //Ye jo bhi dyeing orders hain unko view karney ke liye hian
        public IActionResult ViewDyeingOrders()
        {

ERP_Components/Views/Weaver/Allocationfordying.cshtml
@using ERP_Component_DAL.Models;
@{
    ViewBag.Title = "Allocation for Dying ";
    Layout = "~/Views/Shared/_LayoutINV.cshtml";
}
<link rel="stylesheet" href="~/css/Product.css" />
@model Weaver
<div class="button">
    <button class="me-5 mb-1" onclick="location.href='@Url.Action("SendingForDying", "Weaver")'" id="SendforDying">
        Send for Dying
    </button>
</div>
<div class="table">
    <table>
        <thead>
            <tr>
                <th>Work Order Series </th>
                <th>Product Name</th>
                <th>Specification</th>
                <th>Quantity</th>
                <th>Avaiable For Dying</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><input type="checkbox" class="sendfordying me-3" />WorkOrderSeries</td>
                <td>ProductName</td>
                <td>Specification</td>
                <td>Quantity</td>
                <td>AvailableForDying</td>
            </tr>
            <tr>
                <td><input type="checkbox" class="sendfordying me-3" />WorkOrderSeries</td>
                <td>ProductName</td>
                <td>Specification</td>
                <td>Quantity</td>
                <td>AvailableForDying</td>
            </tr>
        </tbody>
    </table>
</div>

ERP_Components/Views/Weaver/BillOfMaterial.cshtml
@using ERP_Component_DAL.Models;
@model BOM

@{
    ViewBag.Title = "Bill Of Material";
    Layout = "~/Views/Shared/_LayoutINV.cshtml";
}

<link rel="stylesheet" href="~/css/Product.css" />

<form asp-action="CreateBillOfMaterial" asp-controller="Weaver" method="post">
    <div class="form-section">
        <h3>Bill Of Material</h3>

        <div class="form-row" style="width: 50.5%">
            <label for="ProductID">Product Name</label>
            <select id="ProductID" name="ProductID" required>
                <option value="">Select Product</option>
                @foreach (var product in Model.Products)
                {
                    <option value="@product.itemId">@product.itemName - @product.specification</option>
                }
            </select>
        </div>

        <div class="form-row">
            <label for="Material">Material</label>
            <select id="Material">
                <option value="">Select Material</option>
                @foreach (var material in Model.MaterialList)
                {
                    <option value="@material.itemId" data-name="@material.itemName">@material.itemName</option>
                }
            </select>

            <label for="Quantity">Quantity</label>
            <input type="number" id="Quantity" placeholder="Enter Quantity" min="0.01" step="0.01" />
        </div>

        <div class="button">
            <button type="button" id="AddMaterial">Add Material</button>
        </div>
    </div>

    <div id="showtable" class="table" style="margin-top: 30px; display: none;">
        <table>
            <thead>
                <tr>
                    <th>Sr No</th>
                    <th>Material</th>
                    <th>Quantity</th>
                </tr>
            </thead>
            <tbody id="materialListBody">
            </tbody>
        </table>
     </div>
    <div id="hiddenInputsContainer"></div>

    <div id="showbutton" class="button" style="margin-top: 15px;display:none">
        <button type="submit">Submit BOM</button>
    </div>

</form>

<script>
    let materialList = [];
    let srNo = 1;

    document.getElementById("AddMaterial").addEventListener("click", function (e) {
        e.preventDefault();
        const showbutton = document.getElementById("showbutton");
        const showtable = document.getElementById("showtable");
        const materialSelect = document.getElementById("Material");
        const quantityInput = document.getElementById("Quantity");
        const materialId = materialSelect.value;
        const materialName = materialSelect.options[materialSelect.selectedIndex]?.text;
        const quantity = quantityInput.value;

        if (!materialId || !quantity || parseFloat(quantity) <= 0) {
            alert("Please select a material and enter a valid quantity.");
            return;
        }

        showtable.style.display = "block";
        showbutton.style.display = "block";

        const row = document.createElement("tr");
        row.innerHTML = `
            <td>${srNo++}</td>
            <td>${materialName}</td>
            <td>${quantity}</td>
        `;
        document.getElementById("materialListBody").appendChild(row);

        const index = materialList.length;
        const hiddenInputs = `
            <input type="hidden" name="materials[${index}].MatrialID" value="${materialId}" />
            <input type="hidden" name="materials[${index}].Quantity" value="${quantity}" />
            <input type="hidden" name="materials[${index}].MaterialName" value="${materialName}" />
        `;
        document.getElementById("hiddenInputsContainer").insertAdjacentHTML("beforeend", hiddenInputs);

        materialList.push({ materialId, quantity });

        materialSelect.selectedIndex = 0;
        quantityInput.value = "";
    });
</script>

ERP_Components/Views/Weaver/EditWeaver.cshtml
@using ERP_Component_DAL.Models;
@{
    ViewBag.Title = "Edit Weaver";
    Layout = "~/Views/Shared/_LayoutINV.cshtml";
}
<link rel="stylesheet" href="~/css/Product.css" />
@model Weaver
<form asp-action="EditWeaverDetails" asp-controller="Weaver" method="post" enctype="multipart/form-data">
    <div class="form-section">
        <h3>Add Weaver</h3>
        <div class="form-row">
            <input type="hidden" name="WeaverId" value="@Model.WeaverId" />
            <label class="required" for="WeaverName">Weaver Name</label>
            <input type="text" name="WeaverName" id="WeaverName" value="@Model.WeaverName" required />
            <label class="required" for="firm">Firm Name</label>
            <input type="text" name="firm" id="firm" value="@Model.Firm" required />
        </div>
        <div class="form-row">
            <label class="required" for="ContactNumber">Contact Number</label>
            <input type="text" name="ContactNumber" id="ContactNumber" value="@Model.ContactNumber" required />
            <label class="required" for="Email">Email</label>
            <input type="email" name="Email" id="Email" value="@Model.Email" required />
        </div>
        <div class="form-row">
            <label class="required" for="Address">Address</label>
            <input type="text" name="Address" id="Address" value="@Model.Address" required />
            <label class="required" for="City">City</label>
            <input type="text" name="City" id="City" value="@Model.City" required />
        </div>
        <div class="form-row">
            <label class="required" for="District">District</label>
            <input type="text" name="District" id="District" value="@Model.District" required />
            <label class="required" for="State">State</label>
            <input type="text" name="State" id="State"value="@Model.State" required />
        </div>
        <div class="form-row">
            <label class="required" for="Pincode">Pincode</label>
            <input type="text" name="Pincode" id="Pincode" value="@Model.Pincode" required />
            <label class="required" for="Country">Country</label>
            <input type="text" name="Country" id="Country" value="@Model.Country" required />
        </div>
        <div class="form-row">
            <label class="required" for="AadharNumber">Aadhar Number</label>
            <input type="text" name="AadharNumber" id="AadharNumber" value="@Model.AadharNumber" required />
            <label class="required" for="PANNumber">PAN Number</label>
            <input type="text" name="PANNumber" id="PANNumber" value="@Model.PANNumber" required />
        </div>
        <div class="form-row">
            <label class="required" for="docpancard">Photo of PAN:</label>
            <input type="file" name="DocPANCard" id="docpancard" accept="image/*" required />
            <label class="required" for="docaadhar">Photo of Aadhar:</label>
            <input type="file" name="DocAadhar" id="docaadhar" accept="image/*" required />
        </div>
        <div class="button">
            <button type="submit">Update Weaver</button>
        </div>
    </div>
</form>

ERP_Components/Views/Weaver/EditWorker.cshtml
@using ERP_Component_DAL.Models;
@{
    ViewBag.Title = "Edit Weaver";
    Layout = "~/Views/Shared/_LayoutINV.cshtml";
}
<link rel="stylesheet" href="~/css/Product.css" />
@model Worker
<form asp-action="EditWorkerDetails" asp-controller="Weaver" method="post" enctype="multipart/form-data">
    <div class="form-section">
        <h3>Edit Worker</h3>
        <div class="form-row w-50">
          <label for="WorkerType" >Worker Type</label>
            <input type="text" name="WorkerType" id="WorkerType" value="@Model.WorkerType" readonly />
        </div>
        <div class="form-row">
            <input type="hidden" name="WorkerId" value="@Model.WorkerId" />
            <label class="required" for="WorkerName">Weaver Name</label>
            <input type="text" name="WorkerName" id="WeaverName" value="@Model.WorkerName" required />
            <label class="required" for="firm">Firm Name</label>
            <input type="text" name="firm" id="firm" value="@Model.Firm" required />
        </div>
        <div class="form-row">
            <label class="required" for="ContactNumber">Contact Number</label>
            <input type="text" name="ContactNumber" id="ContactNumber" value="@Model.ContactNumber" required />
            <label class="required" for="Email">Email</label>
            <input type="email" name="Email" id="Email" value="@Model.Email" required />
        </div>
        <div class="form-row">
            <label class="required" for="Address">Address</label>
            <input type="text" name="Address" id="Address" value="@Model.Address" required />
            <label class="required" for="City">City</label>
            <input type="text" name="City" id="City" value="@Model.City" required />
        </div>
        <div class="form-row">
            <label class="required" for="District">District</label>
            <input type="text" name="District" id="District" value="@Model.District" required />
            <label class="required" for="State">State</label>
            <input type="text" name="State" id="State"value="@Model.State" required />
        </div>
        <div class="form-row">
            <label class="required" for="Pincode">Pincode</label>
            <input type="text" name="Pincode" id="Pincode" value="@Model.Pincode" required />
            <label class="required" for="Country">Country</label>
            <input type="text" name="Country" id="Country" value="@Model.Country" required />
        </div>
        <div class="form-row">
            <label class="required" for="AadharNumber">Aadhar Number</label>
            <input type="text" name="AadharNumber" id="AadharNumber" value="@Model.AadharNumber" required />
            <label class="required" for="PANNumber">PAN Number</label>
            <input type="text" name="PANNumber" id="PANNumber" value="@Model.PANNumber" required />
        </div>
        <div class="form-row">
            <label class="required" for="docpancard">Photo of PAN:</label>
            <input type="file" name="DocPANCard" id="docpancard" accept="image/*" required />
            <label class="required" for="docaadhar">Photo of Aadhar:</label>
            <input type="file" name="DocAadhar" id="docaadhar" accept="image/*" required />
        </div>
        <div class="button">
            <button type="submit">Update Weaver</button>
        </div>
    </div>
</form>

ERP_Components/Views/Weaver/MaterialRequisitionforWeaver.cshtml
@using ERP_Component_DAL.Models
@{
    ViewBag.Title = "Create Material Requisition";
    Layout = "~/Views/Shared/_LayoutINV.cshtml";
}
<link rel="stylesheet" href="~/css/Product.css" />
@model Weaver

<form method="post" asp-action="SaveMaterialRequisition" asp-controller="Weaver">
    <div class="form-section">
        <h3>Items</h3>
        <div class="form-row">
            <label for="RequisitionSeries">Material Series</label>
            <input type="text" name="RequisitionSeries" id="RequisitionSeries" readonly />

            <label for="ProductName">Item Name</label>
            <input type="text" name="ProductName" value="@Model.ProductName" />
        </div>
        <div class="form-row" style="width:50%">
            <label for="Description">Description</label>
            <input type="text" name="Description" id="Description" />
            <input type="hidden" name="WorkOrderId" value="@Model.WorkOrderId" />
        </div>
    </div>

    <div class="table">
        <table>
            <thead>
                <tr>
                    <th>Material Name</th>
                    <th>Required Quantity</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.MaterialRequired != null && Model.MaterialRequired.Any())
                {
                    for (int i = 0; i < Model.MaterialRequired.Count; i++)
                    {
                        <tr>
                            <td>
                                <input type="hidden" name="MaterialRequired[@i].MaterialName" value="@Model.MaterialRequired[i].MaterialName" />
                                <input type="hidden" name="MaterialRequired[@i].MaterialId" value="@Model.MaterialRequired[i].MaterialId" />
                                @Model.MaterialRequired[i].MaterialName
                            </td>
                            <td>
                                <input type="hidden" name="MaterialRequired[@i].requiredQuantity" value="@Model.MaterialRequired[i].requiredQuantity" />
                                @Model.MaterialRequired[i].requiredQuantity
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr><td colspan="2">No materials found.</td></tr>
                }
            </tbody>
        </table>
    </div>

    <div class="button">
        <button id="submitbtn" type="submit">Submit</button>
    </div>
</form>

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const orderInput = document.getElementById("RequisitionSeries");
            const year = new Date().getFullYear();
            let nextNumber = 1;
            let lastOrder = localStorage.getItem("lastQuotationSeries");

            if (lastOrder) {
                let parts = lastOrder.split("-");
                let lastYear = parseInt(parts[1]);
                let lastNum = parseInt(parts[2]);
                if (lastYear === year) {
                    nextNumber = lastNum + 1;
                }
            }

            const newSeries = `MAR-${year}-${String(nextNumber).padStart(4, "0")}`;
            orderInput.value = newSeries;
            localStorage.setItem("lastQuotationSeries", newSeries);
        });

        const submitbtn = document.getElementById("submitbtn");
        submitbtn.addEventListener("click", function () {
            Swal.fire({
                title: "Created",
                text: "Your Requisition is created",
                icon: "success",
                timer: 1500,
                timerProgressBar: true,
                showConfirmButton: false
            });
        });
    </script>
}

ERP_Components/Views/Weaver/StartWeaving.cshtml
@using ERP_Component_DAL.Models;
@{
    ViewBag.Title = "Start Weaving";
    Layout = "~/Views/Shared/_LayoutINV.cshtml";
}
<link rel="stylesheet" href="~/css/Product.css" />
 @model Weaver
 <style>
    #popup {
        display: none;
        position: fixed;
        top: 10%;
        margin-left: 45px;
        background: #fff;
        padding: 20px;
        box-shadow: 0 0 10px rgba(0,0,0,0.5);
        border-radius: 10px;
        z-index: 999;
        width: 75%;
     }
     #overlay{
        display: none;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: rgba(0,0,0,0.5);
        z-index: 998;
     }
 </style>
 <div class="form-section">
    <h3>Start Weaving</h3>
    <form method="post" asp-action="MoveToOngoing" asp-controller="Weaver">
        <h3>Start Weaving</h3>
        <div class="form-row">
            <label for="workOrderSeries">Work Order Series:</label>
            <input type="text" id="workOrderSeries" name="workOrderSeries" value="@Model.WorkOrderSeries" required />
            <label for="productName">Product Name:</label>
            <input type="text" id="productName" name="productName" value="@Model.ProductName" required />
        </div>
        <div class="form-row">
            <label for="quantity">Quantity:</label>
            <input type="number" id="quantity" name="quantity" value="@Model.Quantity" required />
            <label for="Specification">Specification:</label>
            <input type="text" id="Specification" name="Specification" value="@Model.Specification" required />
        </div>
        <h2>Material Details</h2>
    <div class="table mt-7">
        <table>
            <thead>
                <tr>
                    <th>S.no</th>
                    <th>Material</th>
                    <th> Required Quantity</th>
                    <th>Available Quantity</th>
                </tr>
            </thead>
            <tbody>
                    @for (int i = 0; i < Model.MaterialRequired.Count; i++)
                    {
                        <tr>
                            <td>@(i + 1)</td>
                            <td>@Model.MaterialRequired[i].MaterialName</td>
                            <td>@Model.MaterialRequired[i].requiredQuantity</td>
                            <td>@Model.MaterialRequired[i].availableQuantity</td>
                        </tr>
                    }
            </tbody>
        </table>
    </div>
        <div class="button">
         <button id="showpopup" type="submit">Start Weaving</button>
            <button id="CreateMR"  type="submit">Create MR</button>
        </div>
        <input type="hidden" name="WorkOrderId" value="@Model.WorkOrderId" />
    </form>
 </div>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const createMR = document.getElementById("CreateMR");
        const showpopup = document.getElementById("showpopup");
        const popup = document.getElementById("popup");
        const overlay = document.getElementById("overlay");

        const workOrderId = '@Model.WorkOrderId';

        const required = @Model.MaterialRequired[0].requiredQuantity;
        const available = @Model.MaterialRequired[0].availableQuantity;

        if (required > available) {
            createMR.style.display = "block";
            showpopup.style.display = "none";
        } else {
            createMR.style.display = "none";
            showpopup.style.display = "block";
        }

        showpopup.addEventListener("click", function () {
            popup.style.display = "block";
            overlay.style.display = "block";
        });

        createMR.addEventListener("click", function (e) {
            e.preventDefault();
            window.location.href = `/Weaver/MaterialRequisitionforWeaver?workOrderId=${workOrderId}`;
        });
    });

    function closePopup() {
        document.getElementById("popup").style.display = "none";
        document.getElementById("overlay").style.display = "none";
    }
</script>

ERP_Components/Views/Weaver/ViewCompletedWorkOrder.cshtml
@using ERP_Component_DAL.Models
@{
    ViewBag.Title = "Completed Work Order";
    Layout = "~/Views/Shared/_LayoutINV.cshtml";
}
<link rel="stylesheet" href="~/css/Product.css" />
@model List<Weaver>
<style>
    button {
        justify-self: center;
    }
</style>

    <div class="table">
        <table>
            <thead>
                <tr>
                    <th>Sr No</th>
                    <th>Work Order Series</th>
                    <th>Product Name</th>
                    <th>Quantity</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.Count; i++)
                {
                    var x = Model[i];
                    var index = i + 1;
                    <tr>
                        <td>@index</td>
                        <td>@x.WorkOrderSeries</td>
                        <td>@x.ProductName</td>
                        <td>@x.Quantity</td>
                        <td>
                        <button onclick="location.href='@Url.Action("AllocateToWarehouse","Weaver",new{WorkOrderId = x.WorkOrderId})'">Dispatch</button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>