ERP_Components/Controllers/PurchaseController.cs
using ERP_Component_DAL.Services;
using Microsoft.AspNetCore.Mvc;
using ERP_Component_DAL.Models;
using ERP_Components.Helper;
using ERP_Components.Models;
using System.Diagnostics;


namespace ERP_Components.Controllers
{

    public class PurchaseController : Controller
    {
        private readonly ILogger<PurchaseController> _logger;
        private readonly UserServices _userServices;
        private readonly PurchaseServices purchaseServices;
        private readonly IConfiguration _configuration;

        public PurchaseController(ILogger<PurchaseController> logger, IConfiguration configuration)
        {

            _logger = logger;
            _configuration = configuration;
            _userServices = new UserServices(configuration);
            purchaseServices = new PurchaseServices(configuration);  

        }


        public IActionResult Index()
        {
            
            return View();
        }

        public IActionResult Dashboard()
        {
            DashBoard model = purchaseServices.GetPurchaseDashBoardData();
            return View(model);
        }





        //<---------------------------------Requisition ------------------------------------>

        [HttpGet]
        public IActionResult AddPurchaseRequisition(AddPurchaseRequisition Ap)

        {

            HttpContext.Session.SetString("PurchaseAdded", "False");
            List<AddPurchaseRequisition> data = purchaseServices.GetItemNames();
            return View(data);

        }



        public JsonResult AddpurchaseData(Guid itemId)
        {
            var data = purchaseServices.GetItemsData(itemId);
            return Json(data);
        }

        public JsonResult AddRequisitionItems(AddPurchaseRequisition Ap)
        {
            var PurchaseCreated = HttpContext.Session.GetString("PurchaseAdded");
            if (PurchaseCreated == "False")
            {
                Ap.RequisitionId = purchaseServices.AddRequisition(Ap);
                HttpContext.Session.SetString("PurchaseAdded", "True");
                HttpContext.Session.SetString("RequisitionID", Ap.RequisitionId.ToString());
                var x = purchaseServices.AddPurchaseRequisition(Ap);
            }
            else
            {
                Guid.TryParse(HttpContext.Session.GetString("RequisitionID"), out Guid result);
                Ap.RequisitionId = result;
                purchaseServices.AddPurchaseRequisition(Ap);
            }
            List<AddPurchaseRequisition> purchase = purchaseServices.RequisitionListItems(Ap.RequisitionId);
            var model = new AddPurchaseRequisition()
            {
                listItesms = purchase,
            };
            return Json(model);

        }

        public IActionResult AddRequisition(AddPurchaseRequisition Add)
        {
            Guid.TryParse(HttpContext.Session.GetString("RequisitionID"), out Guid result);
            Add.RequisitionId = result;
            //Console.WriteLine("RequisitionID: " + Add.RequisitionId);
            purchaseServices.UpdateRequisition(Add);
            return RedirectToAction("ViewRequisition");
        }

        public IActionResult ViewRequisition()
        {
            List<AddPurchaseRequisition> list = purchaseServices.ViewRequisitions();
            return View(list);
        }




        public JsonResult ViewRequisitionItemsData(Guid requisitionId)
        {

            List<AddPurchaseRequisition> lists = purchaseServices.GetRequisitionItemsListData(requisitionId);
            return Json(new { list = lists });
        }

      

        public IActionResult DeleteRequisition(Guid RequisitionId)
        {
            purchaseServices.DeleteRequisition(RequisitionId);
            return RedirectToAction("ViewRequisition");
        }

        //<-----------------------Purchase Order--------------------->


        public IActionResult CreatePurchaseOrder()
        {
            List<AddPurchaseRequisition> requisitions = purchaseServices.ApprovedRequisitions();
            return View(requisitions);
        }


        public IActionResult PurchaseOrder(Guid requisitionId)
        {
            Vendor vendor = purchaseServices.GetVendorDataForOrder(requisitionId);
            List<AddPurchaseRequisition> Item = purchaseServices.GetPurchasedOrdersItemsLists(requisitionId);

            vendor.Items = Item;

            return View(vendor);
        }






        //public IActionResult SetPurchaseOrder(List<AddPurchaseRequisition> AddRequisition)
        //{

        //    return View();
        //}

        public IActionResult UpdateRequisitionStatusToClosed(Vendor vendor)
        {
           
            Guid.TryParse(HttpContext.Session.GetString("RequisitionID"), out Guid result);

            Guid purchaseOrderID = Guid.NewGuid();
            purchaseServices.AddPurchaseOrder(vendor, purchaseOrderID);
            purchaseServices.AddPurchaseOrderItems(vendor.Items, purchaseOrderID);
            purchaseServices.AddTaxDetails(purchaseOrderID, vendor);
            purchaseServices.UpdateRequisitionStatusToClosed(vendor);
            return RedirectToAction("CreatePurchaseOrder");
        }

        public IActionResult ViewPurchaseOrder()
        {

            List<Vendor> vendor = purchaseServices.ViewFinalPurchaseOrder();
            return View(vendor);
        }


        public IActionResult GeneratePurchaseOrder()
        {

            List<Vendor> vendor = purchaseServices.GeneratePurchaseOrder();
            return View(vendor);
        }


        public IActionResult PurchaseOrderForm(Guid vendorId, Guid purchaseOrderId)
        {

            Vendor vendor = purchaseServices.GetVendorAddressDetails(vendorId);
            List<AddPurchaseRequisition> ItemData = purchaseServices.PurchaseOrderItemsList(vendorId, purchaseOrderId, PurchaseOrderStatus.ITEMS_RECEIVED);
            vendor.Items = ItemData;
            return View(vendor);
        }

        [HttpPost]
        public IActionResult AddPurchaseInvoice([FromBody] Vendor vendor)
        {
            purchaseServices.AddPurchaseBill(vendor);
            return RedirectToAction("PurchaseBills");
        }


       


        public IActionResult PurchaseBills()
        {
         List<Vendor> vendor =   purchaseServices.GeneratePurchaseBill();
            return View(vendor);
        }



        public IActionResult GeneratePurchaseInvoice(Guid vendorId, Guid purchaseOrderId)
        {

            Vendor vendor = purchaseServices.GetPurchaseBills(purchaseOrderId);
            List<AddPurchaseRequisition> ItemData = purchaseServices.PurchaseOrderItemsList(vendorId, purchaseOrderId, PurchaseOrderStatus.CONVERTED_TO_BILL);
            vendor.Items = ItemData;
            return View(vendor);
        }




        //<-----------------------Vendor Quotation ------------------------->

        public IActionResult CreateVendorQuotation()
        {
            List<AddPurchaseRequisition> add = purchaseServices.ApprovedRequisitionsForQuotation();

            return View(add);
        }


        public IActionResult VendorQuotation(Guid requisitionId)
        {
            var vendor = new Vendor();
            vendor.requisitionId = requisitionId;
            vendor.vendor = purchaseServices.GetVendorNames();
            vendor.lists = purchaseServices.GetRequisitionQuotationListData(requisitionId);
            vendor.Items = purchaseServices.GetPurchaseRequisitionItems(requisitionId);

            return View(vendor);
        }

        public JsonResult SetQuotation(Vendor vendor)
        {
            Guid vendorQuotationID =  purchaseServices.AddVendorQuotation(vendor);
            purchaseServices.AddVendorQuotationItems(vendor, vendorQuotationID);
            List<Vendor> lists = purchaseServices.GetRequisitionQuotationListData(vendor.requisitionId);
            return Json(lists);
        }


       
       public IActionResult ChangePurchaseStatus(Vendor vendor)
        {
            purchaseServices.UpdateRequisitionStatusToPending(vendor.requisitionId);
            return RedirectToAction("CreateVendorQuotation");
        }




        public IActionResult ViewVendorQuotation()
        {
            List<AddPurchaseRequisition> quotation = purchaseServices.ViewRequisitionsForQuotation();
            return View(quotation);
        }



        





        public JsonResult ViewQuotationVendorData(Guid requisitionId)
        {

            List<Vendor> lists = purchaseServices.GetRequisitionQuotationListData(requisitionId);
            return Json(new { list = lists });
        }


        public IActionResult UpdateRequisitionStatusToQuotationApproved(Guid RequisitionID)
        {
            purchaseServices.UpdateRequisitionStatusToQuotationApproved(RequisitionID);
            return RedirectToAction("ViewVendorQuotation");
        }
        public IActionResult ViewStorePR()
        {
            List<Store_PR> storePRList = purchaseServices.FindStorePR(StorePRStatus.PENDING);
            return View(storePRList);
        }


        public IActionResult CreatePurchaseRequisition(List<Store_PR> selectedIds)
        {
            List<PurchaseRequisitionItems> purchaseRequisitionItems = new List<PurchaseRequisitionItems>();
            for(int i = 0; i < selectedIds.Count; i++)
            {
                bool isAvailabe = false;
                for(int j = 0; j < purchaseRequisitionItems.Count; j++)
                {
                    if (selectedIds[i].item.itemId == purchaseRequisitionItems[j].itemId)
                    {
                        isAvailabe = true;
                        purchaseRequisitionItems[j].quantity += selectedIds[i].Quantity;
                        purchaseRequisitionItems[j].storePRIDs.Add(selectedIds[i].StorePRID);
                    }
                }
                if (!isAvailabe)
                {
                    var prItem = new PurchaseRequisitionItems
                    {

ERP_Components/Views/Purchase/AddPurchaseRequisition.cshtml
@using ERP_Component_DAL.Models;

@{
	ViewBag.Title = "Add Requisition";
	Layout = "~/Views/Shared/_LayoutINV.cshtml";
}


<link rel="stylesheet" href="/css/Product.css" />


@model List<AddPurchaseRequisition>

<div class="form-section">
<h3>Create Requisition</h3>
<form id="purchaseForm">
	
		<div class="form-row">
			<label for="category">Select Item</label>
			<div class="dropdown-container" style="position: relative; width:36%">
				<div id="customDropdown" class="dropdown-button" onclick="toggleDropdown()" style="border: 1px solid #ccc; padding: 5px; width: 100%; cursor: pointer;">
					Select Item
				</div>
				<div id="dropdownList" class="dropdown-list"
					 style="position: absolute; top: 100%; left: 0; width: 100%; display: none; max-height: 200px; overflow-y: auto; border: 1px solid #ccc; background: white; z-index: 1000;">
					<input type="text" id="searchInput" onkeyup="filterItems()" placeholder="Search..."
						   style="width: 95%; margin: 5px; padding: 5px;">
					<ul id="itemList" style="list-style: none; padding: 0; margin: 0;">
						@for (var i = 0; i < Model.Count; i++)
						{
							<li onclick="selectItem('@Model[i].itemId', '@Model[i].itemName')"
								style="padding: 8px; cursor: pointer;">@Model[i].itemName</li>
						}
					</ul>
				</div>
			</div>

			<input type="hidden" id="selectedItemId" name="itemId" />

			<label for="category">Category</label>
			<input id="cat" type="text" name="category">
			<input type="hidden" id="hiddenQuotationSeries" />




		</div>


	<div class="form-row">
			<label for="sku">Unit Price</label>
			<input id="unitPrice" type="number" name="unitPrice">
				<label for="specification">Specification</label>
				<input id="specf" type="text" name="specification">
		</div>

	

	
		

		<div class="form-row">
			<label for="unitofmeasure">UOM</label>
			<input id="uom" type="text" name="unitofmeasure">
			<label for="gst">GST %</label>
			<input id="Gst" type="number" name="gst">
		</div>

		


		<div class="form-row">
			<label for="itemtype">Item Type</label>
			<input id="itype" type="text" name="itemtype">
			<input id="itemId" type="hidden" name="itemId">

			<label for="hsncode">HSN</label>
			<input id="hsn" type="text" name="HSN">
		</div>

	


		<div class="form-row" style="width:50%">
			<label for="qty">Quantity</label>
			<input id="quantity" type="number" name="quantity">
			<input type="hidden" id="reqId" name="RequisitionId" />

		</div>


</form>

	<div class="button-container">

	<button type="submit" id="addItems">Add</button>
</div>
</div>

<form method="post" asp-action="AddRequisition" asp-controller="Purchase" style="width:95%; margin-top:80px;">


	


 <div class="table">

		<table>
			<thead>
				<tr>
					<th>Requisition Series</th>
					<th>Description </th>
					<th>Total Amount</th>
					<th>Raised By</th>
					<th>Required By</th>
				</tr>

				<tr>
					<td><input type="text" id="RequisitionSeries" name="requisitionSeries" readonly></td>
					<td><input type="text" name="Descripion"></td>
					<td><input type="text" id="totalAmountInput" name="TotalAmount"></td>
					<td><input type="text" name="RaisedBy"></td>
					<td><input type="text" name="RequiredBy"></td>

				</tr>
		</table>

	</div> 


	<div class="button-container">

		<button type="submit">Submit</button>
	</div>
</form>


<div class="table">
	<table>
		<thead>
			<tr>
				<th>S.No</th>
				<th>Item Name</th>
				<th>Category</th>
				<th>Specification</th>
				<th>UOM</th>
				<th>Item Type</th>
				<th>HSN</th>
				<th>Quantity</th>
				<th>Unit Price</th>
				<th>Total Amount</th>

			</tr>
		</thead>

		<tbody id="TableBody">
		</tbody>

	</table>
</div>






<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


<script>
	function toggleDropdown() {
		document.getElementById("dropdownList").style.display =
			document.getElementById("dropdownList").style.display === "none" ? "block" : "none";
	}

	function filterItems() {
		var input = document.getElementById("searchInput");
		var filter = input.value.toLowerCase();
		var ul = document.getElementById("itemList");
		var li = ul.getElementsByTagName("li");

		for (var i = 0; i < li.length; i++) {
			var txtValue = li[i].textContent || li[i].innerText;
			li[i].style.display = txtValue.toLowerCase().indexOf(filter) > -1 ? "" : "none";
		}
	}

	function selectItem(id, name) {
		document.getElementById("customDropdown").innerText = name;
		document.getElementById("selectedItemId").value = id;
		document.getElementById("dropdownList").style.display = "none";


		$('#selectedItemId').trigger('change');
	}


	document.addEventListener('click', function (event) {
		const dropdown = document.querySelector('.dropdown-container');
		if (!dropdown.contains(event.target)) {
			document.getElementById("dropdownList").style.display = "none";
		}
	});
</script>
<script>
	function selectItem(id, name) {
		document.getElementById("customDropdown").innerText = name;
		document.getElementById("selectedItemId").value = id;
		document.getElementById("dropdownList").style.display = "none";


		if (id) {
			$.ajax({
				url: "/Purchase/AddpurchaseData",
				type: "GET",
				data: { itemId: id },
				success: function (data) {
					if (data) {
						$('#itemId').val(data.itemId);
						$('#reqId').val(data.reqId);
						$('#iname').val(data.itemname);
					  $('#unitPrice').val(data.unitPrice);
						$('#cat').val(data.category);
						$('#specf').val(data.specification);
						$('#uom').val(data.unitofmeasure);
						$('#Gst').val(data.gst);
						$('#itype').val(data.itemtype);
						$('#hsn').val(data.hsn);
					} else {
						alert("Product not found");
					}
				},
				error: function() {
					alert("Error fetching item data");
				}
			});
		}
	}

</script>

<script>
	$(document).ready(function () {
		$("#addItems").click(function () {
			var formData = {
				itemId: $('#itemId').val(),
				Itemname: $('#iname').val(),
				unitPrice: $('#unitPrice').val(),
				category: $('#cat').val(),
				specification: $('#specf').val(),
				unitofmeasure: $('#uom').val(),
				gst: $('#Gst').val(),
				itemtype: $('#itype').val(),
				hsn: $('#hsn').val(),
				quantity: $('#quantity').val()
			};

			$.ajax({
				type: 'POST',
				url: '/Purchase/AddRequisitionItems',
				data: formData,
					success: function (response) {
		console.log("Success:", response);

		let tableBody = document.getElementById("TableBody");
		let totalAmountSum = 0;
		tableBody.innerHTML = "";

		$(response.listItesms).each(function (index, item) {
			var seq = index + 1;
			totalAmountSum += parseFloat(item.totalAmount);

			const tr = document.createElement("tr");
			tr.innerHTML = `
				<td>${seq}</td>
				<td>${item.itemName}</td>
				<td>${item.category}</td>
				<td>${item.specification}</td>
				<td>${item.unitofmeasure}</td>
				<td>${item.itemtype}</td>
				<td>${item.hsn}</td>
				<td>${item.quantity}</td>
				<td>${item.unitPrice}</td>
				<td>${item.totalAmount}</td>
			`;
			tableBody.appendChild(tr);
		});

		$("#totalAmountInput").val(totalAmountSum.toFixed(2));

	
		$("#iname").val("");
		$("#itemId").val("");
		$("#unitPrice").val("");
		$("#cat").val("");
		$("#specf").val("");
		$("#uom").val("");
		$("#Gst").val("");
		$("#itype").val("");
		$("#hsn").val("");
		$("#quantity").val("");
		$("#customDropdown").text("Select Item");
		$("#selectedItemId").val("");
	},

				
				error: function (xhr, status, error) {
					console.error("Error:", xhr.responseText);
					alert("Failed to add item.");
				}
			});
		});
	});
</script>




<script>
	document.addEventListener("DOMContentLoaded", function () {
		const orderInput = document.getElementById("RequisitionSeries");
		const hiddenInput = document.getElementById("hiddenQuotationSeries");

		const year = new Date().getFullYear();
		let nextNumber = 1;

	
		let lastOrder = localStorage.getItem("lastQuotationSeries");

		if (lastOrder) {
			let parts = lastOrder.split("-");
			let lastYear = parseInt(parts[1]);
			let lastNum = parseInt(parts[2]);

			if (lastYear === year) {
				nextNumber = lastNum + 1;
			}
		}

		const newSeries = `REQ-${year}-${String(nextNumber).padStart(4, "0")}`;


		orderInput.value = newSeries;
		hiddenInput.value = newSeries;

		localStorage.setItem("lastQuotationSeries", newSeries);
	});
	
</script>

ERP_Components/Views/Purchase/CreatePurchaseOrder.cshtml
@using ERP_Component_DAL.Models;

@{
	ViewBag.Title = "Create Purchase Order";
	Layout = "~/Views/Shared/_LayoutINV.cshtml";
}

<link rel="stylesheet" href="/css/Product.css" />



@model List<AddPurchaseRequisition>

<div class="table">



	<table>
		<thead>
			<tr>
				<th>S.No.</th>
				<th>Req. Series</th>
				<th>Description</th>
				<th>Date</th>
				<th>Total Amount</th>
				<th>Actions</th>
			</tr>
		</thead>



		<tbody id="geeks">


			@for (var i = 0; i < Model.Count; i++)
			{

				var x = Model[i];
				var index = i + 1;

				<tr id="row-@x.">
					<td>@index</td>
					<td>@x.requisitionSeries</td>
					<td>@x.Descripion</td>
					<td>@x.Date.ToShortDateString()</td>
					<td>@x.TotalAmount</td>
					<td>
						<div class="table-button">


							<button onclick="location.href='@Url.Action("PurchaseOrder", "Purchase", new { requisitionId = @x.RequisitionId }, null)'">Create Order</button>
							@* <button onclick="location.href='@Url.Action("DeleteRequisition", "Home", new { RequisitionId = @x.RequisitionId }, null)'">Reject</button> *@


						</div>
					</td>

				</tr>
			}
		</tbody>

	</table>




</div>

ERP_Components/Views/Purchase/CreatePurchaseRequisition.cshtml
@using ERP_Component_DAL.Models;
  @model List<PurchaseRequisitionItems>

@{
    ViewBag.Title = "Create Purchase Requisition";
    Layout = "~/Views/Shared/_LayoutINV.cshtml";
}

<link rel="stylesheet" href="/css/Product.css" />

<div id="material">
    <form method="post" asp-action="SetCreatePurchaseRequisition" asp-controller="Purchase">



        <div class="form-section">
            <h3>Vendor Info</h3>
            <div class="form-row">
                <label for="PurchaseRequisition">Purchase Requisition Series</label>
                <input type="text" name="requisitionSeries" value="PR-0010-2025" readonly />

                <label class="required" for="totalTaxableAmount">Amount:</label>
                <input type="text" id="totalTaxableAmount" name="totalAmount" value="" required readonly />
            </div>

            <div class="form-row" style="width:50%">
                <label class="required" for="description">Description:</label>
                <textarea name="description"></textarea>
            </div>
        </div>

        <div>
            <table>
                <thead>
                    <tr>
                        <th>S.No.</th>
                        <th>Item Name</th>
                        <th>Quantity</th>
                        <th>Rate</th>
                        <th>Taxable Value</th>
                    </tr>
                </thead>
                <tbody id="geeks">
                    @for (int i = 0; i < Model.Count; i++)
                    {
                        var item = Model[i];
                        <tr>
                            <td>@(i + 1)</td>

                            <td>
                                <input type="text" name="purchaseRequisitionItems[@i].itemName" value="@item.itemName" readonly />
                                <input type="hidden" name="purchaseRequisitionItems[@i].itemId" value="@item.itemId" />
                            </td>

                            <td>
                                <input type="number" name="purchaseRequisitionItems[@i].Quantity" value="@item.quantity"
                                class="quantity" data-index="@i" />
                            </td>

                            <td>
                                <input type="number" name="purchaseRequisitionItems[@i].unitPrice" value="@item.unitPrice"
                                class="unit-price" data-index="@i" />
                            </td>

                            <td>
                                <input type="number" name="purchaseRequisitionItems[@i].TotalAmount" value="@item.totalAmount"
                                class="total-amount" data-index="@i" readonly />
                            </td>
                            @for(int j=0;j< item.storePRIDs.Count;j++)
                            {

                                <input type="hidden" name="purchaseRequisitionItems[@i].storePRIDs[@j]" value="@item.storePRIDs[j]" />
                            }

                        </tr>
                    }
                </tbody>
            </table>
        </div>


        <div class="button">
            <button type="reset">Reset</button>
            <button id="submitted" type="submit">Submit</button>
        </div>
    </form>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        function updateTotals() {
            let totalTaxable = 0;

            const rows = document.querySelectorAll('#geeks tr');
            rows.forEach(row => {
                const quantityInput = row.querySelector('.quantity');
                const priceInput = row.querySelector('.unit-price');
                const totalInput = row.querySelector('.total-amount');

                const quantity = parseFloat(quantityInput?.value) || 0;
                const price = parseFloat(priceInput?.value) || 0;

                const total = quantity * price;
                if (totalInput) {
                    totalInput.value = total.toFixed(2);
                }
                totalTaxable += total;
            });

            document.getElementById('totalTaxableAmount').value = totalTaxable.toFixed(2);
        }

        // Bind input listeners
        document.querySelectorAll('.quantity, .unit-price').forEach(input => {
            input.addEventListener('input', updateTotals);
        });

        // Initial calculation
        updateTotals();
    });
</script>


<script>
        document.addEventListener("DOMContentLoaded", function () {
        const orderInput = document.getElementById("requisitionSeries");

        const year = new Date().getFullYear();
        let nextNumber = 1;

        let lastOrder = localStorage.getItem("lastrequisitionSeries");

        if (lastOrder) {
            let parts = lastOrder.split("-");
            let lastYear = parseInt(parts[1]);
            let lastNum = parseInt(parts[2]);

            if (lastYear === year) {
                nextNumber = lastNum + 1;
            }
        }

        const newSeries = `PRS-${year}-${String(nextNumber).padStart(4, "0")}`;


        orderInput.value = newSeries;
        hiddenInput.value = newSeries;

        localStorage.setItem("lastrequisitionSeries", newSeries);
    });
</script>

ERP_Components/Views/Purchase/CreateVendorQuotation.cshtml
@using ERP_Component_DAL.Models;
@{
	ViewBag.Title = "Create Vendor Quotation";
	Layout = "~/Views/Shared/_LayoutINV.cshtml";
}

<link rel="stylesheet" href="/css/Product.css" />


@model List<AddPurchaseRequisition>

<div class="table">



	<table >
		<thead>
			<tr>
				<th>S.No.</th>
				<th>Req. Series</th>
				<th>Description</th>
				<th>Date</th>
				<th>Total Amount</th>
				<th>Actions</th>
			</tr>
		</thead>



		<tbody id="geeks">


			@for (var i = 0; i < Model.Count; i++)
			{

				var x = Model[i];
				var index = i + 1;

				<tr id="row-@x.">
					<td>@index</td>
					<td>@x.requisitionSeries</td>
					<td>@x.Descripion</td>
					<td>@x.Date.ToShortDateString()</td>
					<td>@x.TotalAmount</td>
					<td>
						<div class="table-button">


							<button onclick="location.href='@Url.Action("VendorQuotation", "Purchase", new { requisitionId = @x.RequisitionId }, null)'">Create Quotation</button>



						</div>
					</td>

				</tr>
			}
		</tbody>

	</table>




</div>

ERP_Components/Views/Purchase/PurchaseBills.cshtml
@using ERP_Component_DAL.Models;

@{
	ViewBag.Title = "Purchase Order";
	Layout = "~/Views/Shared/_LayoutINV.cshtml";
}
<link rel="stylesheet" href="/css/Product.css" />




@model List<Vendor>

<div class="table">

	<table>
		<thead>
			<tr>
				<th>S.No.</th>
				<th>Vendor Name</th>
				<th>Vendor Code</th>
				<th>Bill Number</th>
				<th>Created At</th>
				<th>Paid Amount</th>
				<th>Actions</th>
			</tr>
		</thead>



		<tbody id="geeks">


			@for (var i = 0; i < Model.Count; i++)
			{

				var x = Model[i];
				var index = i + 1;

				<tr id="row-@x.vendorId; @x.purchaseOrderId">

					<td>@index</td>
					<td>@x.vendorName</td>
					<td>@x.vendorCode</td>
					<td>@x.invoiceNumber</td>
					<td>@x.createdAt.ToShortDateString()</td>
					<td>@x.amount</td>
					<td>
						<div class="table-button">

							<button onclick="location.href='@Url.Action("GeneratePurchaseInvoice", "Purchase", new { vendorId = @x.vendorId, purchaseOrderID = @x.purchaseOrderId }, null)'">View Purchase Bills</button>
							@* <button type="button" class="convert-btn" data-purchase-id="@x.purchaseOrderId">Convert To Bill</button> *@

						</div>
					</td>

				</tr>
			}
		</tbody>

	</table>




</div>