ERP_Components/Controllers/SalesController.cs
using ERP_Component_DAL.Models;
using ERP_Component_DAL.Services;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;

namespace ERP_Components.Controllers
{
    public class SalesController : Controller
    {
        private readonly ILogger<SalesController> _logger;
        private readonly SalesServices salesServices;
        private readonly CenterlizedService centerlizedService;
        private readonly IConfiguration _configuration;
        private List<QuotationModel> quotationModels = new List<QuotationModel>();


        public SalesController(ILogger<SalesController> logger, IConfiguration configuration, CenterlizedService centerlizedService)
        {
            _logger = logger;
            _configuration = configuration;
            salesServices = new SalesServices(configuration);
            this.centerlizedService = centerlizedService;
        }
        public IActionResult Dashboard()
        {
            return View();
        }




        //Quotation  
        public IActionResult ManageQuotation()
        {
            List<QuotationModel> QL = salesServices.ListQuotation();

            return View(QL);

        }
        //edit Quotaion 
        public IActionResult EditQuotation(Guid QuotationID)//int QuotationID
        {


            List<QuotationModel> EQ = salesServices.EditQuota(QuotationID); //remaining2
            return View(EQ);
        }
        public IActionResult EditQuotationDetails(QuotationModel q)
        {

            salesServices.updateEditPro(q);


            return View();
        }
        public IActionResult EditQuotationform(QuotationModel e)
        {
            salesServices.finalEditQuota(e);
            salesServices.editAmount(e);
            return RedirectToAction("ManageQuotation");
        }


        public IActionResult AddQuotation()
        {
            HttpContext.Session.SetString("QuotationAdded", "False");
            List<QuotationModel> aq = salesServices.GetProductDetails();
            List<QuotationViewModel.Customer> Customers = salesServices.GetCustomersList();

            var model = new QuotationViewModel
            {
                ItemNames = aq,
                Customers = Customers
            };

            return View(model);
        }






        [HttpPost]
        public IActionResult SetQuotation(QuotationModel quotation,List<QuotationModel> ItemLists)
        {
            salesServices.AddQuotation(quotation, ItemLists);
            return RedirectToAction("AddQuotation");
        }



        //delete Quotation

        public IActionResult DeleteQuota(QuotationModel q)
        {
            salesServices.DeleteQuotation(q);
            return RedirectToAction("ManageQuotation");
        }


        public IActionResult ViewQuotation(Guid QuotationID)
        {
            //salesServices.ViewQuotationDoc(vq, QuotationID);
            //List<QuotationModel> pl = salesServices.ShowProductLi(QuotationID);
            List<QuotationModel> pl = salesServices.ViewQuotationDoc(QuotationID);
            return View(pl);
        }



        ////Product
        //public IActionResult ProductView()
        //{
        //    List<Products> pl = salesServices.AddCategory();
        //    return View(pl);
        //}
        //public JsonResult ItemName(int CategoryID)
        //{

        //    List<Products> pl = salesServices.AddItemName(CategoryID);
        //    return Json(pl);
        //}



        //invoice 
        public IActionResult ManageInvoice()
        {
            List<Invoice> IL = salesServices.ListInvoice();
            return View(IL);
        }

        //create invoice
        public IActionResult AddInvoice(Guid QuotationID)
        {
            //HttpContext.Session.SetString("invoiceAdded", "False");

            //List<Invoice> In = salesServices.InvoiceQvalue(QuotationID);

            InvoiceForm? invoice = salesServices.GetInvoiceFromQuotation(QuotationID);
            return View(invoice);
        }
        public IActionResult SetAddInvoice(Invoice q)
        {
            //TODO: Fix this controller
            Console.WriteLine("We are in SetAdd Invoice");
            q.InvoiceID = salesServices.AddInvoiceDetails(q);
            salesServices.SaveShipingDetails(q);
            //salesServices.TransportDetail(q);
            //salesServices.DispatchDetail(q);
            //salesServices.CourierDetail(q);
            salesServices.Updatestatus(q);




            return RedirectToAction("ManageInvoice");
        }

        public IActionResult DispatchInvoice(Guid InvoiceID)
        {
            return View(InvoiceID);
        }

        public IActionResult AddDispatchDetails(Dispatch dispatch)
        {    
            salesServices.SaveDispatchDetails(dispatch);
            return RedirectToAction("ManageInvoice");
        }

        public IActionResult CancelInvoice(Invoice I, Guid InvoiceID)
        {
            salesServices.CancelInvoice(I, InvoiceID);
            return RedirectToAction("ManageInvoice");
        }


        public IActionResult EditInvoice(Guid InvoiceID)  
        {
            List<Invoice> li = new List<Invoice>();
            li.Add(salesServices.EditInvoice(InvoiceID));
            li.Add(salesServices.ViewShippedTo(InvoiceID));
            li.Add(salesServices.ViewTransportDetails(InvoiceID));
            li.Add(salesServices.ViewDispatchDetails(InvoiceID));
            li.Add(salesServices.ViewCourierDetails(InvoiceID));
            return View(li);
        }
        [HttpPost]
        public IActionResult UpdateEditInvoice(Invoice i)
        {
            salesServices.updateInvoice(i);

            return RedirectToAction("ManageInvoice");
        }




        public IActionResult ViewInvoice(Guid InvoiceID, Guid QuotationID)
        {
            InvoiceView iv = new InvoiceView();
            iv.ProductView = salesServices.ViewInvoiceProd(QuotationID);
            iv.ListView = new List<Invoice>
            {

            salesServices.EditInvoice(InvoiceID),
            salesServices.ViewShippedTo(InvoiceID),
            salesServices.ViewTransportDetails(InvoiceID),
            salesServices.ViewDispatchDetails(InvoiceID),
            salesServices.ViewCourierDetails(InvoiceID),

            };
            iv.BusinessSetUp = salesServices.GetBusinessSetUp();
            return View(iv);
        }
         //ProformaInvoice
        public IActionResult ManageProformaInvoice()
        {
            List<ProformaInvoice> IL = salesServices.ListProformaInvoice();
            return View(IL);
        }
        public IActionResult ProformaInvoice()
        {
            return View();
        }
        public IActionResult SetProformaInvoice(ProformaInvoice Pi)
        {
            salesServices.Proformainvoice(Pi);
            return RedirectToAction("ManageProformaInvoice");
        }

        public IActionResult DeleteProformaInvoice(ProformaInvoice P, Guid ProformaInvoiceID)
        {
            salesServices.DeleteProforma(P, ProformaInvoiceID);
            return RedirectToAction("ManageProformaInvoice");
        }
        public IActionResult EditProforma(ProformaInvoice p, Guid ProformaInvoiceID)
        {
            var x = salesServices.EditProformaInvoice(p, ProformaInvoiceID);
            return View(x);
        }
        public IActionResult UpdateEdit(ProformaInvoice p)
        {
            salesServices.UpdateProfoma(p);
            return RedirectToAction("ManageProformaInvoice");
        }
        //CreditNote

        public IActionResult ManageCreditNote()
        {
            List<CreditNote> CL = salesServices.ListCreditNote();
            return View(CL);
        }
        public IActionResult CreditNote()
        {
            return View();
        }
        public IActionResult SetCreditNote(CreditNote c)
        {
            salesServices.CreditNote(c);
            return RedirectToAction("ManageCreditNote");
        }
        public IActionResult EditCreditNote(CreditNote c, Guid CreditNoteId)
        {
            var x = salesServices.EditCreditNote(c, CreditNoteId);
            return View(x);
        }
        public IActionResult UpdateCreditNote(CreditNote c)
        {
            salesServices.UpdateCreditNote(c);
            return RedirectToAction("ManageCreditNote");
        }
        public IActionResult DeleteCreditNote(CreditNote c, Guid CreditNoteId)
        {
            salesServices.DeleteCreditNote(c, CreditNoteId);
            return RedirectToAction("ManageCreditNote");
        }

        //ReturnNote
        public IActionResult ReturnNote(bool y)
        {
            ViewBag.loaded = y;
            List<ReturnNote> lr = salesServices.ListReturnNote();
            return View(lr);
        }
        public IActionResult SetReturnNote(ReturnNote r)
        {
            salesServices.CreateReturnNote(r);
            bool x = true;
            return RedirectToAction("ReturnNote", new { y = x });
        }
        public IActionResult DeleteReturnNote(ReturnNote r, Guid ReturnNoteId)
        {
            salesServices.DeleteReturnNote(r, ReturnNoteId);
            bool x = true;
            return RedirectToAction("ReturnNote", new { y = x });
        }
        public IActionResult EditReturnNote(ReturnNote r, Guid ReturnNoteId)
        {
            var x = salesServices.EditReturnNote(r, ReturnNoteId);
            return View(x);
        }
        public IActionResult UpdateReturnNote(ReturnNote r)
        {
            salesServices.UpdateReturnNote(r);
            bool x = true;
            return RedirectToAction("ReturnNote", new { y = x });
        }

        //DeliveryChallan
        public IActionResult ManageDeliveryChallan()
        {
            List<DeliveryChallan> D = salesServices.ListDeliveryChallan();
            return View(D);
        }

        public IActionResult DeliveryChallan()
        {
            return View();
        }

ERP_Components/Views/Sales/CreditNote.cshtml
@using ERP_Component_DAL.Models
@{
    ViewBag.Title = "AddCreditNote";
    Layout = "~/Views/Shared/_LayoutINV.cshtml";
}

<link rel="stylesheet" href="~/css/ProductTwo.css" />

@* 
<div class="toggle-buttons" style="margin-left: 28px;">
    <button type="button" class="button" onclick="showSection('basic')">Basic Details</button>
    <button type="button" class="button" onclick="showSection('additional')" style="margin-left:10px;">Additional Details</button>
</div> *@

<form method="" asp-action="SetCreditNote" asp-controller="Sales">

    <!-- BASIC DETAILS SECTION -->
    <div class="form-section">
        <h3>Basic Details</h3>
        <div class="form-row">
                <label for="orderSeries">OrderSeries ID</label>
                <input type="text" id="orderSeriesID" name="OrderSeriesID" >
           
            
                <label for="creditNoteFor">Credit Note For</label>
                <select id="creditNoteFor" name="CreditNoteFor" >
                    <option selected value="">Select</option>

                    <option value="customer">Customer</option>
                    <option value="vendor">Vendor</option>
                </select>
            </div>
        <div class="form-row">
                <label for="creditNoteType">Credit Note Type</label>
                <select id="creditNoteType" name="CreditNoteType">
                    <option  selected value="">Select</option>
                    <option value="sales return">Sales Return</option>
                    <option value="post sales discount">Post Sales Discount</option>
                    <option value="Deficiency in same">Deficiency in same</option>
                    <option value="Correcting In Invoice">Correcting In Invoice</option>
                    <option value="Change in POS">Change in POS</option>

                    <option value="other">Other</option>
                </select>

                <label for="creditNote">Credit Note Date</label>
                <input type="date" id="creditNoteDate" name="CreditNoteDate">
         
       </div>
        <div class="form-row">
        @* <div class="form-row" style="display: flex; justify-content: space-between; padding-left: 72px; padding-right: 209px;"> *@
                <label for="customerName">Customer Name</label>
                <input type="text" id="customerName" name="CustomerName" >
            
       
                <label for="invoiceNumber">Invoice Number</label>
                <input type="text" id="invoiceNumber" name="InvoiceNumber" >
        
     </div>

   </div>
        <!-- SHIPPING DETAILS SECTION -->
    <div class="form-section">
        
        <h3>Shipping Details</h3>
        <div class="form-row">
   
                <label for="numberOfCartons">Number of Cartons</label>
                <input type="number" id="numberOfCartons" name="NumberOfCartons" >
       
                <label for="lorryReceiptNumber">Lorry Receipt Number</label>
                <input type="text" id="lorryReceiptNumber" name="LorryReceiptNumber">
            </div>
        <div class="form-row">
                <label for="lorryReceiptDate">Lorry Receipt Date</label>
                <input type="date" id="lorryReceiptDate" name="LorryReceiptDate">
      
        
                <label for="modeOfShipment">Mode of Shipment</label>
                <input type="text" id="modeOfShipment" name="ModeOfShipment" >
            </div>
        <div class="form-row" style="width:50%">
                <label for="remarks">Remarks</label>
                <input type="text" id="remarks" name="Remarks" >
       
    </div>
    </div>
    <!-- ADDITIONAL DETAILS SECTION -->
    <div class="form-section">

        <h3>Additional Details</h3>
        <div class="form-row">
 
                <label for="costCenter">Cost Center</label>
                <select id="costCenter" name="CostCenter">
                    <option value="">-- Select Cost Center --</option>
                    <option value="Account">Account</option>
                    <option value="Products">Products</option>
                    <option value="Service">Service</option>
                    @* <option value="admin">Admin</option> *@
                </select>
            
                <label for="location">Location</label>
                <input type="text" id="location" name="Location">
             </div>
        <div class="form-row" style="width:50%">
                <label for="noteId">Customer/Vendor Note ID</label>
                <input type="text" id="noteId" name="VenderNoteId">
            </div>
       
</div>
    <div>
        <button class="button" type="submit" style=" float: right;margin-top: 18px;margin-right: 47px; margin-bottom: 13px;  background-color:#138496;color: white;">
            submit
        </button>
    </div>

</form>


<script>

    document.addEventListener("DOMContentLoaded", function () {
        const orderInput = document.getElementById("orderSeriesID");
        const year = new Date().getFullYear();
        let nextNumber = 1;

        // Get the last order series from localStorage
        let lastOrder = localStorage.getItem("lastQuotationSeries");

        if (lastOrder) {
            let parts = lastOrder.split("-");
            let lastYear = parseInt(parts[1]);
            let lastNum = parseInt(parts[2]);

            if (lastYear === year) {
                nextNumber = lastNum + 1;
            }
        }

        const newSeries = `CDN-${year}-${String(nextNumber).padStart(4, "0")}`;

        // Set the input values
        orderInput.value = newSeries;

        // Store the new series in localStorage
        localStorage.setItem("lastQuotationSeries", newSeries);
    });
</script>












@* <script>
    function showSection(section) {
        const basic = document.getElementById('basicSection');
        const additional = document.getElementById('additionalSection');

        if (section === 'basic') {
            basic.style.display = 'block';
            additional.style.display = 'none';
        } else {
            basic.style.display = 'none';
            additional.style.display = 'block';
        }
    }

    // Default view is Basic Section
    window.onload = function () {
        showSection('basic');
    };
</script> *@

ERP_Components/Views/Sales/DeliveryChallan.cshtml
@{
    ViewBag.Title = "DeliveryChallan";
    Layout = "~/Views/Shared/_LayoutINV.cshtml";
}

<link rel="stylesheet" href="~/css/ProductTwo.css" />

<form method="post" asp-action="SetDeliveryChallan" asp-controller="Sales">
    <div class="form-section">
        <h3>Basic Details</h3>
        <div class="form-row">
        <label for="">Delivery Challan Type</label>
        <select id="" name="DeliveryChallanType" >
            <option value="Normal Gate Pass">Normal Gate Pass</option>
            <option value="Return Gate Pass">Return Gate Pass</option>
            <option value=""></option>
        </select>
   
        <label for="">Branch</label>
        <input type="text" id="" name="Branch" >
    </div>
        <div class="form-row">
            <label for="OrderSeries">Order Series ID</label>
            <input type="text" id="orderSeriesID" name="OrderSeriesID">

    



        <label > Security Seal number</label>
        <input type="text" id="" name="SecuritySealNumber">
    </div>

            <div class="form-row">

        <label for="customerName">Customer Name</label>
        <input type="text" id="customerName" name="CustomerName" >
        <label for="ChallanDate">Challan Date</label>
        <input type="Date" id="" name="ChallanDate" >
    </div>


        <button class="button" type="submit" style=" float: right;margin-top: 70px;margin-right: -15px; background-color:#138496;color: white;">
            submit
        </button>
    </div>
</form>

<script>

    document.addEventListener("DOMContentLoaded", function () {
        const orderInput = document.getElementById("orderSeriesID");
        const year = new Date().getFullYear();
        let nextNumber = 1;

        // Get the last order series from localStorage
        let lastOrder = localStorage.getItem("lastQuotationSeries");

        if (lastOrder) {
            let parts = lastOrder.split("-");
            let lastYear = parseInt(parts[1]);
            let lastNum = parseInt(parts[2]);

            if (lastYear === year) {
                nextNumber = lastNum + 1;
            }
        }

        const newSeries = `DLC-${year}-${String(nextNumber).padStart(4, "0")}`;

        // Set the input values
        orderInput.value = newSeries;

        // Store the new series in localStorage
        localStorage.setItem("lastQuotationSeries", newSeries);
    });
</script>

ERP_Components/Views/Sales/DispatchInvoice.cshtml
@using ERP_Component_DAL.Models
@model Guid
@{
    ViewBag.Title = "Dispatch Invoice";
    Layout = "~/Views/Shared/_LayoutINV.cshtml";
}
<link rel="stylesheet" href="~/css/Product.css" />

<form asp-controller="Sales" asp-action="AddDispatchDetails" method="post">
    <input type="hidden" id="InvoiceID" name="InvoiceID" value="@Model" />
                        <div class="form-section">
                            <h3>Transport/E-Way Bill</h3>
                                <div class="form-row">
                                    <label>Transporter ID:</label>
                                    <input type="text" id="TransporterID" name="TransporterID" placeholder="Enter Transporter ID">

                                    <label>Mode Of Shipment:</label>
                                    <select id="ModeOfShipment" name="ModeOfShipment" style="padding: 5px;width: 250px !important;">
                                        <option value="">Select Mode of Shipment</option>
                                        <option value="Air">Air</option>
                                        <option value="Road">Road</option>
                                        <option value="Rail">Rail</option>
                                        <option value="Sea">Sea</option>
                                    </select>
                                </div>
                                <div class="form-row">

                                    <label>Transport Document Number:</label>
                                    <input type="text" id="" name="TransporterDocumentNumber" placeholder="Enter Transporter Doc Number">
                                    <label>GR.Number:</label>
                                    <input type="text" id="GRNumber" name="GRNumber" placeholder="Enter GR Number">
                                  </div>
                                  <div class="form-row">
                                        <label>Number Of Cartons:</label>
                                        <input type="number" id="NumberOfCartons" name="NumberOfCartons" placeholder="Enter Cartons">
                                        <label>Transporter Name:</label>
                                        <input type="text" id="TransporterName" name="TransporterName" placeholder="Enter Transporter Name">
                                  </div>
                                    <div class="form-row">
                                        <label>Vehicle Type:</label>
                                        <input type="text" id="VehicleType" name="VehicleType" placeholder="Enter Type Of Vehicle">
                                        <label>Transporter Document Date:</label>
                                        <input type="date" id="" name="TransporterDocumentDate">
                                    </div>
                                    <div class="form-row">
                                        <label>Net Weight:</label>
                                        <input type="number" id="NetWeight" name="NetWeight" placeholder="Enter Net Weight">
                                        <label>Transaction Type:</label>
                                        <input type="text" id="TransactionType" name="TransactionType" placeholder="Enter Transaction Type">
                                    </div>

                                   <div class="form-row">
                                        <label>Distance (KM):</label>
                                        <input type="number" id="DistanceKM" name="DistanceKM" placeholder="Enter Distance(KM)">

                                        <label>Vehicle Number:</label>
                                        <input type="text" id="VehicleNumber" name="VehicleNumber" placeholder="Enter Vehicle Number">
    
                                    </div>
                                   <div class="form-row">
                      
                                        <label> Time Of Supply :</label>
                                        <input type="time" id="TimeOfSupply" name="TimeOfSupply">
                                        <label>Gross Weight:</label>
                                        <input type="number" id="GrossWeight" name="GrossWeight" placeholder="Enter Gross Weight">
                                   </div>
                                   <div class="form-row" style="width:50%">
                                        <label>Freight charges:</label>
                                        <select id="FreightCharges" name="FreightCharges" style="padding: 5px;width: 250px !important;">
                                            <option value="">Select</option>
                                            <option value="Paid">Paid</option>
                                            <option value="Unpaid">Unpaid</option>

                                        </select>

                                   </div>
                        </div>
                        <div id="form3" class="form-section">
                            <!-- Dispatch Form Content -->
                            <h3>Dispatch </h3>
                            <h3>Dispatch Details</h3>


                                <div class="form-row">
                                    <label>Location Name:</label>
                                    <input type="text" id="AddressLine1" name="AddressLine1" placeholder="Enter Location">
                                    <label>Districts:</label>
                                    <input type="text" id="District" name="District" placeholder="Enter Districts">

                                </div>

                                <div class="form-row">
                                    <label>Area :</label>
                                    <input type="text" id="Area" name="Area" placeholder="Enter Area">

                                    <label>City:</label>
                                    <input type="text" id="City" name="City" placeholder="Enter City">


                                </div>

                                <div class="form-row">
                                    <label>State:</label>
                                    <input type="text" id="State" name="State" placeholder="Enter State">

                                    <label>PIN Code:</label>
                                    <input type="text" id="Pincode" name="Pincode" placeholder="Enter PIN Code">

                                </div>
                                <div class="form-row">
                                    <label>Corrier Details:</label>
                                    <input type="text" id="CourierDetail" name="CourierDetail" placeholder="Enter Corrier Details">


                                    <label>Corrier Company:</label>
                                    <input type="text" id="CourierCompany" name="CourierCompany" placeholder="Enter Company">
                                </div>

                                <div class="form-row" style="width:50%">
                                    <label>Tracking Number:</label>
                                    <input type="text" id="TrackingNumber" name="TrackingNumber" placeholder="Enter Tracking Number">


                                </div>
                                <div class="button">
                                    <button type="submit">submit</button>
                                </div>
                        </div>


</form>

ERP_Components/Views/Sales/EditProforma.cshtml
@using ERP_Component_DAL.Models

@{
    ViewBag.Title = "Edit ProformaInvoice";
    Layout = "~/Views/Shared/_LayoutINV.cshtml";
}

<link rel="stylesheet" href="~/css/ProductTwo.css" />
 
 @model ProformaInvoice
<form method="post" asp-action="UpdateEdit" asp-controller="Sales">
@*     <h2>Basic Details</h2>

    <div id="basicSection" class="cntr2">
        <div class="form-row" style=" display: flex;justify-content: space-between;padding-left: 72px; padding-right: 209px;">
            <div class="form-group">
                <label for="orderSeries">OrderSeries ID</label>
                <input type="text" id="" name="OrderSeriesID" value="@Model.OrderSeriesID" style=" width: 228px !important;">
            </div>
            <div class="form-group">
                <label for="paymentTerm">Payment Term</label>
                <input type="text" id="PaymentTerm" name="PaymentTerm"  value="@Model.PaymentTerm"style=" width: 228px !important;">
            </div>
        </div>
        <div class="form-row" style=" display: flex;justify-content: space-between;padding-left: 72px; padding-right: 209px;" >
            <div class="form-group">
                <label for="customerName">Customer Name</label>
                <input type="text" id="CustomerName" name="CustomerName" value="@Model.CustomerName" style=" width: 228px !important;">
            </div>
            <div class="form-group">
                <label for="deliveryTerm">Delivery Term</label>
                <input type="text" id="DeliveryTerms" name="DeliveryTerms" value="@Model.DeliveryTerms" style=" width: 228px !important;">
            </div>
        </div>
    </div>

    <h2 style=" margin-top: 16px;margin-bottom: 16px;">
        Additional Details
    </h2>
    <div id="additionalSection" class="cntr2">
        <div class="form-row" style=" display: flex;justify-content: space-between;padding-left: 72px; padding-right: 209px;">
            <div class="form-group">
                <label for="proformaRef">PO Ref Number</label>
                <input type="text" id="POReferenceNumber" name="POReferenceNumber" value="@Model.POReferenceNumber" style=" width: 228px !important;">
            </div>
            <div class="form-group">
                <label for="vendorCode">Vendor Code</label>
                <input type="text" id="VenderCode" name="VenderCode" value="@Model.VenderCode" style=" width: 228px !important;">
            </div>
        </div>
        <div class="form-row" style=" display: flex;justify-content: space-between;padding-left: 72px; padding-right: 209px;">

            <div class="form-group">
                <label for="poDate">PerformaDate</label>
                <input type="text" id="PODate" name="PODate" value="@Model.PODate" readonly >
            </div>
            <div class="form-group">
                <label for="JobCode">JobCode</label>
                <input type="text" id="" name="JobCode" value="@Model.JobCode" style=" width: 228px !important;">
            </div>
        </div>

    </div>
    <input type="text" value="@Model.ProformaInvoiceID" name="ProformaInvoiceID" hidden />
    <input type="hidden" value="@Model.TermConditionID" name="TermConditionID" hidden />
    <div>
        <button class="button" type="submit" style=" float: right;margin-top: 18px;margin-right: 13px;">submit</button>
    </div>

 *@






    <div class="form-section">

        <h3>Basic Details</h3>
        <div class="form-row">



            <label for="orderSeries">OrderSeries ID</label>
            <input type="text" id="" name="OrderSeriesID" value="@Model.OrderSeriesID" >

            <label for="paymentTerm">Payment Term</label>
            <input type="text" id="PaymentTerm" name="PaymentTerm" value="@Model.PaymentTerm">
        </div>
        <div class="form-row">

            <label for="customerName">Customer Name</label>
            <input type="text" id="CustomerName" name="CustomerName" value="@Model.CustomerName" >

            <label for="deliveryTerm">Delivery Term</label>
            <input type="text" id="DeliveryTerms" name="DeliveryTerms" value="@Model.DeliveryTerms">
        </div>
    </div>

    <div class="form-section">

        <h3>
            Additional Details
        </h3>
        <div class="form-row">

            <label for="proformaRef">PO Ref Number</label>
            <input type="text" id="POReferenceNumber" name="POReferenceNumber" value="@Model.POReferenceNumber" >

            <label for="vendorCode">Vendor Code</label>
            <input type="text" id="VenderCode" name="VenderCode" value="@Model.VenderCode" >
        </div>
        <div class="form-row">

            <label for="poDate">PerformaDate</label>
            <input type="text" id="PODate" name="PODate" value="@Model.PODate" readonly>

            <label for="Jobcode">Job Code</label>
            <input type="text" id="" name="JobCode" value="@Model.JobCode" >

        </div>
    </div>
    <input type="text" value="@Model.ProformaInvoiceID" name="ProformaInvoiceID" hidden />
    <input type="hidden" value="@Model.TermConditionID" name="TermConditionID" hidden />
    <div>
        <button class="button" type="submit" style=" float: right;margin-top: 18px;margin-right: 52px; background-color:#138496;color: white;">
            submit
        </button>
    </div>
</form>